# Specify which provider to use globally
provider: openai

llm:
  openai:
    model_name: gpt-4o
    temperature: 0.0
    max_tokens: 2048
    api_key: ${OPENAI_API_KEY}

  ollama:
    model_name: qwen2.5:7b-instruct
    temperature: 0.0
    format: json

embedding:
  openai:
    model_name: text-embedding-3-small
    dimensions: 1536
    api_key: ${OPENAI_API_KEY}

  ollama:
    model_name: nomic-embed-text